parser: '@typescript-eslint/parser'
settings:
  react:
    version: detect
  import/core-modules:
    - react
    - styled-jsx/css
plugins:
  - react
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
env:
  browser: true
  es2021: true
  node: true
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
rules:
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-member-accessibility': off
  '@typescript-eslint/indent': off
  '@typescript-eslint/member-delimiter-style': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-empty-function': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/ban-types':
    - 2
    - types:
        Function: false
        Object: false
  import/no-extraneous-dependencies: 2 # very important!
  react/display-name: off
  react/prop-types: off
